function generateColdEmailDrafts() {
    const API_KEY = "YOUR_GEMINI_API_KEY_HERE"; // <--- Put your free Gemini API key here
    const sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
    const data = sheet.getDataRange().getValues();

    // 1. YOUR RESUME BACKGROUND CONTEXT
    const myBackground = `
  Sender Name: Sujal Bhati
  Education: B.Tech in Electrical Engineering at Delhi Technological University (DTU).
  Key Technical Experience: 
  - Full-stack development: Building custom React frontends hosted on Vercel, backends with Supabase, and deploying self-hosted CRM/ERP instances (Frappe/ERPNext) on virtual private servers (VPS).
  - Cybersecurity: Ethical hacking, organizing Capture The Flag (CTF) challenges, vulnerability analysis, and active society leadership.
  - Robotics/Embedded Systems: Junior Software Lead for Team Inferno DTU (ROS frameworks, space drone electrical and software subsystems).
  `;

    // 2. COLD EMAIL MASTERY PROMPT RULES
    const emailRules = `
  - Write a punchy, hyper-targeted cold outreach email trying to secure a software engineering, AI/ML, or hardware/software internship or role.
  - Keep the email incredibly short: 3 to 4 sentences maximum. No long blocks of text.
  - Drop all formal AI fluff: NEVER use phrases like "I hope this email finds you well", "My name is...", "Dear Hiring Team", or "I am writing to express my interest".
  - Jump directly into a highly specific observation about their company using the Industry or Company Description provided. Make it sound like an organic observation a sharp student noticed.
  - Ground your relevance by naturally mentioning a piece of your background (e.g., building full-stack platforms on VPS, ROS frameworks, or security testing) that solves or complements what they do.
  - Sound like an ambitious, skilled individual writing casually yet respectfully. Avoid overly corporate corporate buzzwords (e.g., 'delighted', 'synergy', 'testament', 'foster').
  - End with a low-friction, single-sentence Call to Action (CTA) asking if they have 2 minutes for a brief chat or if you can drop over a 60-second video demonstrating your stack.
  `;

    // Start loop from index 1 to skip your header row (Row 1)
    for (let i = 1; i < data.length; i++) {
        let recruiterName = data[i][1];      // Column B
        let recruiterEmail = data[i][2];     // Column C
        let recruiterTitle = data[i][3];     // Column D
        let companyName = data[i][4];        // Column E
        let industry = data[i][6];           // Column G
        let companyDescription = data[i][7]; // Column H
        let status = data[i][8];             // Column I (We use this for tracking)

        // Only process if there's an email and status isn't already marked "Drafted"
        if (recruiterEmail && status !== "Drafted" && status !== "Skipped") {

            const prompt = `
      You are an expert executive copywriter. Draft a short, razor-sharp cold email based on these raw details.
      
      Sender Context:
      ${myBackground}
      
      Structural Framework Constraints:
      ${emailRules}
      
      Recipient Information:
      - Name: ${recruiterName} (Title: ${recruiterTitle})
      - Company Name: ${companyName}
      - Industry: ${industry}
      - What the Company Does: ${companyDescription}
      
      Output format requirement: 
      Line 1 must be exactly: Subject: [Your compelling, brief subject line here]
      Line 2 onwards must be the email body. Do not include any signature block placeholders (like [Your Name]). End directly at the call to action sentence. No markdown formatting or bold markers.
      `;

            // Hit the Gemini 2.5 Flash free tier endpoint
            const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${API_KEY}`;
            const payload = {
                "contents": [{ "parts": [{ "text": prompt }] }]
            };

            const options = {
                "method": "post",
                "contentType": "application/json",
                "payload": JSON.stringify(payload),
                "muteHttpExceptions": true
            };

            try {
                const response = UrlFetchApp.fetch(url, options);
                const json = JSON.parse(response.getContentText());

                if (!json.candidates || json.candidates.length === 0) {
                    throw new Error("No response generated by the model. Check rate limits.");
                }

                const aiResponse = json.candidates[0].content.parts[0].text;

                // Parse the generated text into subject and body variables
                let lines = aiResponse.split('\n');
                let subject = `Quick question regarding ${companyName}`;
                let body = aiResponse;

                if (lines[0].toLowerCase().startsWith("subject:")) {
                    subject = lines[0].replace(/subject:/i, "").trim();
                    body = lines.slice(1).join('\n').trim();
                }

                // Sign off cleanly with your name
                body += "\n\nBest,\nSujal Bhati";

                // Create the draft dynamically inside your Gmail
                GmailApp.createDraft(recruiterEmail, subject, body);

                // Mark column I as Drafted so it skips this row next time you press run
                sheet.getRange(i + 1, 9).setValue("Drafted");
                SpreadsheetApp.flush();

            } catch (e) {
                Logger.log("Error processing row " + (i + 1) + ": " + e.toString());
                sheet.getRange(i + 1, 9).setValue("Error");
                SpreadsheetApp.flush();
            }

            // 2-second timeout to avoid hammering the free API tier rate limits
            Utilities.sleep(2000);
        }
    }
}